name: all-checks
on:
  push:
    branches:
      - master
  pull_request:
env:
  GO_VERSION: 1.14
jobs:
  all-checks:
    name: checks
    runs-on: ubuntu-latest
    steps:
    - name: set up go ${{env.GO_VERSION}}
      uses: actions/setup-go@v1
      with:
        go-version: ${{env.GO_VERSION}}
    - name: Add bin to path # required to execute build tools
      run: echo "::add-path::${{env.GOPATH}}/bin"
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Install build tools
      run: go install github.com/gojuno/minimock/v3/cmd/minimock
    - name: Run go generate
      run: go generate ./...
    - name: Run tests
      run: go test -count=1 -v ./...
    - name: Check code coverage
      run: |
        go test -coverprofile=coverage.tmp.out ./...
        cat coverage.tmp.out | grep -v _mock.go > coverage.out
        go tool cover -html=coverage.out -o coverage.html
#    - name: Upload coverage to Codecov
#      run: ./scripts/codecov-upload.sh -f ./coverage.out -y ./.codecov.yml -n coverage-report -F
    - name: Add coverage.out to artifacts
      uses: actions/upload-artifact@v1
      with:
        name: coverage-out
    - name: Add coverage.html to artifacts
      uses: actions/upload-artifact@v1
      with:
        name: coverage-html
